### ISSUE TITLE
Two mods missing from client-side mods list

### ISSUE THREAD

**Issue by Nevrai** [nanonestor/universalator#10]
**Operating System version (i.e. Windows version, etc):**
Windows 11

**Universalator version:**
2.34

**Describe the bug**
I found two client-side mods that are not caught by Universalator’s scan feature.

* [**Cubes Without Borders**](https://www.curseforge.com/minecraft/mc-mods/cubes-without-borders)
* [**Slotify**](https://www.curseforge.com/minecraft/mc-mods/slotify)

**Comment by nanonestor** [comment]
Added, thanks
