### ISSUE TITLE
MaFgLib Causes Crashes

### ISSUE THREAD

**Issue by NFLD99** [nanonestor/universalator#11]
**Operating System version (i.e. Windows version, etc):**
22h2 Windows 10 Pro

**Universalator version:**
2.31

**Describe the bug**
[mafglib](https://www.curseforge.com/minecraft/mc-mods/mafglib) is a client side mod {or at least one that causes crashes on the server side} that isnt sorted out via the scan option

**Screenshots**
N/A

**Comment by nanonestor** [comment]
Thank you - added.

2.31 is a bit old - I suggest you get a copy of the newest version, 2.36
