### ISSUE TITLE
Feature Request: Default to LZ4 Compression

### ISSUE THREAD

**Issue by Git-North** [nanonestor/universalator#13]
New versions of minecraft can utilize LZ4 compressed region files by a simple change in server.properties file, since this project has no problem modfying "allow-flight" I believe this addition would fit right in.

**Comment by nanonestor** [comment]
Hmmmm that's right. So LZ4 takes up more disk space but gives greater performance vs the standard 'deflate'.  Hmm let's see just how much we're talking - i'll do some tests as this does not get talked about much.

**Comment by nanonestor** [comment]
Casual numbers i'm getting shows 36% larger, but that's just a stock Neoforge 20.4 with a pregen radius of 1000 blocks.

I'll add it to totally-there-but-doesn't-get-much-public-relations 'properties editing' menu with some logic to make sure it's only one or the other that can be used!

**Comment by nanonestor** [comment]
Added region-file-compression to the PROPS menu that toggles between 'deflate' and 'LZ4' when selected.
