### ISSUE TITLE
Feature Request: Use different java distrubutions

### ISSUE THREAD

**Issue by Git-North** [nanonestor/universalator#15]
Adoptium java lacks certain features that make it incompatible with some mods, most notably performance ones (FasterRandom)
it also has a inferior garbage collector compared to other java distrubutions

I have made a PR that already made this change alongside some other things

**Comment by Git-North** [comment]
https://github.com/nanonestor/universalator/pull/12

**Comment by nanonestor** [comment]
As discussed, will be leaving the Universalator JVMs being used as Adoptium (and Adoptium, with needed fill-ins for OS/arch compatibility holes, on the Linux edition)
