### ISSUE TITLE
Feature Request: use aikars flags by default

### ISSUE THREAD

**Issue by Git-North** [nanonestor/universalator#16]
Very simple change that adds performance benefits while not modifying any Server-related files.

I have made a PR that implements this along other changes

**Comment by Git-North** [comment]
https://github.com/nanonestor/universalator/pull/12

**Comment by nanonestor** [comment]
Actually changed default args in 2.37 to be CPWs args :)

And made the ARGS default to blank if 1- launching Java 17 and newer, and 2- ARGS have not been edited/changed by the user to something custom.
