### ISSUE TITLE
pinging to mojang server failed

### ISSUE THREAD

**Issue by founderali** [nanonestor/universalator#6]
**Operating System version (i.e. Windows version, etc):**
Windows 10 Pro version 10.0.19045 19045
**Universalator version:**
2.27

**Describe the bug**
Trying to run it, everything is going fine when I'm entering the settings for the server, input 1.16.5, FORGE, i write Y for latest, 8 for java and then input 10GB. I launch and Universalator attempts to ping from Mojang file server and request is timed out and not working. I ping both
ping launchermeta.mojang.com
ping piston-meta.mojang.com
in cmd, both requests are timed out. I ping google.com and it works, ping my own ip and it works, other websites work too, it's just mojang and I don't know what to do.

**Screenshots**
![image](https://github.com/nanonestor/universalator/assets/155511612/ef218cbd-946e-4630-98ba-290e984ac232)

**Comment by nanonestor** [comment]
Greetings.  This issue has cropped up with multiple people and it might be that Mojang started doing ICMP blocking to prevent pings.  Various other people have reported this lately also, including myself - so in the Universalator update today to 2.28 I no longer do ping checks to the Mojang websites.  Files still download from the sites, as they are supposed to.
