### ISSUE TITLE
JAVA BINARIES ZIP FILE FAILED TO DOWNLOAD

### ISSUE THREAD

**Issue by S-K1NG** [nanonestor/universalator#8]
**Operating System version 
Windows 10

**Universalator version:**
2.31

When I try to launch the server, it keeps looping this text:

 Downloading Java 21 newest version from Adoptium

At line:1 char:385
+ ... bClient).DownloadFile($data.binaries.package.link, 'C:\Valor's Server ...
+                                                                  ~
Missing ')' in method call.
At line:1 char:385
+ ... Client).DownloadFile($data.binaries.package.link, 'C:\Valor's Server\ ...
+                                                                 ~
Unexpected token 's' in expression or statement.
At line:1 char:426
+ ... s.package.link, 'C:\Valor's Server\univ-utils\java\javabinaries.zip')
+                                                                        ~~
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

  JAVA BINARIES ZIP FILE FAILED TO DOWNLOAD - PRESS ANY KEY TO TRY AGAIN

  Retrying Adoptium Java download...
  Retrying  Adoptium Java download..
  Retrying  Adoptium Java download.

**Screenshots**

![JAVA](https://github.com/user-attachments/assets/873eab92-6384-497c-94e6-248f19c1f9e8)

**Comment by S-K1NG** [comment]
The same thing happens if I choose Java 17.

**Comment by nanonestor** [comment]
Try removing the apostrophe in your folder name.  It is not a good idea to use special characters in folder and file names, because different programs interpret them differently.

**Comment by S-K1NG** [comment]
> Try removing the apostrophe in your folder name. It is not a good idea to use special characters in folder and file names, because different programs interpret them differently.

YEP, that did it!
Thank you so much!
